### ISSUE TITLE
What does the GPL mean for Arduino projects?

### ISSUE THREAD

**Issue by cellularmitosis** [enjoyneering/HTU2xD_SHT2x_Si70xx#1]
First, thanks for open sourcing such a high quality library.

I'm familiar with how the GPL (and LGPL) work for Linux libraries, but I'm not as sure about libraries for the Arduino.

On the Arduino, all of the code ultimately gets compiled into the same hex binary.  So it seems like any sketch which uses this library _must_ be GPL'ed as well.

Is that correct?

If so, would you consider releasing this under something like MIT?

**Comment by enjoyneering** [comment]
Hi cellularmitosis, 

This is description of GPL - https://www.gnu.org/licenses/licenses.html

Basically it is free,  but you need to release your code (share it for free with everyone). If this is not what you want, you should probably look for another library.

**Comment by cellularmitosis** [comment]
Thanks for the reply.

You may be interested in a library I recently wrote called "AnyWire", an abstraction which allows using hardware and software I2C together: https://github.com/pepaslabs/AnyWire

I also added support for AnyWire into a forked copy of HTU2xD_SHT2x_Si70xx in that repo, so that it can be used with both software and hardware I2C.

This was the specific context which had me puzzled a bit by licensing.

This is my guess:
- Obviously, my modified version of HTU2xD_SHT2x_Si70xx must be GPL'ed
- The demo.ino sketch uses HTU2xD_SHT2x_Si70xx, so I think it must also be GPL'ed?
- AnyWire itself does not directly touch HTU2xD_SHT2x_Si70xx, so I think I can still release that under MIT.

**Comment by enjoyneering** [comment]
As long as you and your clients keep code open and have a link to original files (my git) I'm OK.
